name: Dummy Site
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3205249682068825
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7a7a7a'
    - '#969696'
    - '#bbbbbb'
    - '#535353'
    - '#e8e8e8'
  brandStrength: 1
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
